### ISSUE TITLE
 Does not show the mobile navigation bar

### ISSUE THREAD

**Issue by Jenderz** [i-amdroid/material_base#2]
When you perform the installation and create some test pages, when you try the responsive mode it does not show the mobile navigation bar in Drupal 8. 

![2018-06-04-183224_1024x600_scrot](https://user-images.githubusercontent.com/33388647/40929638-a7ead9b2-6825-11e8-881a-7d8230810290.png)

![2018-06-04-183440_1024x600_scrot](https://user-images.githubusercontent.com/33388647/40929759-fb930210-6825-11e8-8ea7-64d4036b1cda.png)

Help me.

**Comment by i-amdroid** [comment]
Yes, it is.
By default, mobile navigation doesn't create automatically.
You have to do it manually.
In general, you need at least 3 custom blocks:

1. Navbar menu toggle

`<div id="navbar-menu-toggle" ><a href="#"><i class="material-icons navbar-icon">menu</i></a></div>`

Region: Navbar

Id is important. Also add classes like "navbar-item", "hidden-sm" to the block.

2. Drawer close button and site or menu title

```
<div id="drawer-menu-close"><a href="#"><i class="material-icons drawer-icon">arrow_back</i></a></div>
<div id="drawer-title">Sections</div>
```

Region: Drawer

Id is important. Also add classes like "drawer-item", "divider-bottom" to the block.

3. Place instance of you main menu to Drawer region

Don't forget to add class "drawer-item" to the block.

Also you could check docs http://mb.4dx.pw/components and examples http://mb.4dx.pw/examples

**Comment by Jenderz** [comment]
Thank you very much! I was perfect, but ignorance ignores. I would like to place the **Header background**, I have tried but I can do it. Could you help me?

**Comment by i-amdroid** [comment]
It is very easy. Did you tried this http://mb.4dx.pw/components#header-region ?
What exactly not work?

**Comment by Jenderz** [comment]
This is what I did: I created a new custom block called header1. I added the code:

```
<div class="block">
  <img id="bg-object" src="img/header-bg.jpg">
</div>

```
 then I added it to the region Header background. When I go to start nothing happens.

**Comment by i-amdroid** [comment]
Also you need to add `header-bg-object` class to body tag and put something to header content region.
